name: Xcode - Build and Analyze

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build flutter project on mac os
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.10.4'
        architecture: x64
    - run: flutter clean
    - run: flutter pub get
    - run: echo 'String authToken = "AeeIXUMjbmR0A";' >> ./lib/tokens.dart
    - run: echo 'String folderId = "e0w_LoUGeoIXUMjbmR0A";' >> ./lib/tokens.dart
    - run: echo 'String googleEng = "eGeoIXUMjbmR0A";' >> ./lib/tokens.dart
    - run: echo 'String googleToken = "eUMjbmR0A";' >> ./lib/tokens.dart
    - run: flutter build ios --release --no-codesign
